version: '3'

services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    networks:
      - nginx-proxy
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: password
      VIRTUAL_HOST: deversify-cms.dev.snajd.se

  db:
    image: mongo
    networks:
      - nginx-proxy
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017

networks:
  nginx-proxy:
    external: true
